<?php
/** Theme link locations that are not stored in the content tree. */
defined( 'ABSPATH' ) || exit;
return array(
	'header_login' => array( 'group' => 'header', 'default' => 'https://www.momentum.network/', 'label' => 'Member Login — desktop and mobile' ),
		'about_joseph_varghese_joseph_story' => array( 'group' => 'about_joseph_varghese', 'default' => '#joseph-story', 'label' => 'Discover His Story' ),
		'about_joseph_varghese_contact_us' => array( 'group' => 'about_joseph_varghese', 'default' => '/contact-us/', 'label' => 'Contact Us' ),
		'momentum_buddy_buddy_how_it_works' => array( 'group' => 'momentum_buddy', 'default' => '#buddy-how-it-works', 'label' => 'How It Works' ),
		'momentum_buddy_buddy_included' => array( 'group' => 'momentum_buddy', 'default' => '#buddy-included', 'label' => 'What’s Included' ),
		'momentum_buddy_buddy_members' => array( 'group' => 'momentum_buddy', 'default' => '#buddy-members', 'label' => 'Member Stories' ),
		'momentum_buddy_pricing' => array( 'group' => 'momentum_buddy', 'default' => '#pricing', 'label' => 'View Membership Options' ),
		'momentum_buddy_application' => array( 'group' => 'momentum_buddy', 'default' => 'https://www.momentumbuddy.com/#_fw4dxl5ri', 'label' => 'Apply — hero, pricing and closing buttons' ),
		'momentum_os_programs' => array( 'group' => 'momentum_os', 'default' => '#programs', 'label' => 'Programs' ),
		'momentum_os_weekly_cycle' => array( 'group' => 'momentum_os', 'default' => '#weekly-cycle', 'label' => 'Explore the Six Steps' ),
		'momentum_os_momentum_buddy' => array( 'group' => 'momentum_os', 'default' => '/momentum-buddy/', 'label' => 'Momentum Buddy' ),
		'momentum_os_momentum_labs' => array( 'group' => 'momentum_os', 'default' => '/momentum-labs/', 'label' => 'Momentum Labs' ),
		'momentum_os_momentum_team' => array( 'group' => 'momentum_os', 'default' => '/momentum-team/', 'label' => 'Momentum Team' ),
		'faq_page_faq_test' => array( 'group' => 'faq', 'default' => '#test', 'label' => 'Entrepreneur test' ),
		'contact_us_sc_contact_form' => array( 'group' => 'contact_us', 'default' => '#sc-contact-form', 'label' => 'Send Us a Message' ),
		'contact_us_faq' => array( 'group' => 'contact_us', 'default' => '/faq/', 'label' => 'Faq' ),
		'weekly_wins_wins' => array( 'group' => 'weekly_wins', 'default' => '#wins', 'label' => 'Explore Member Wins' ),
		'testimonials_member_films' => array( 'group' => 'testimonials', 'default' => '#member-films', 'label' => 'Watch Member Stories' ),
		'testimonials_member_letters' => array( 'group' => 'testimonials', 'default' => '#member-letters', 'label' => 'Read Their Experiences' ),
		'momentum_labs_labs_founder' => array( 'group' => 'momentum_labs', 'default' => '#labs-founder', 'label' => 'Meet the Founder' ),
		'momentum_labs_labs_membership' => array( 'group' => 'momentum_labs', 'default' => '#labs-membership', 'label' => 'Explore Membership' ),
		'momentum_labs_labs_support' => array( 'group' => 'momentum_labs', 'default' => '#labs-support', 'label' => 'Your Support System' ),
		'momentum_team_pricing' => array( 'group' => 'momentum_team', 'default' => '#pricing', 'label' => 'Program Investment' ),
		'momentum_team_team_apply' => array( 'group' => 'momentum_team', 'default' => '#team-apply', 'label' => 'How to Apply' ),
		'momentum_team_team_roadmap' => array( 'group' => 'momentum_team', 'default' => '#team-roadmap', 'label' => 'Explore the 90 Days' ),
		'momentum_team_team_stories' => array( 'group' => 'momentum_team', 'default' => '#team-stories', 'label' => 'Member Stories' ),
		'momentum_team_team_support' => array( 'group' => 'momentum_team', 'default' => '#team-support', 'label' => 'What’s Included' ),
		'about_corevalues' => array( 'group' => 'about', 'default' => '#corevalues', 'label' => 'Our Values' ),
		'about_founder' => array( 'group' => 'about', 'default' => '#founder', 'label' => 'Meet the Founder' ),
		'about_our_approach' => array( 'group' => 'about', 'default' => '#our-approach', 'label' => 'Our Approach' ),
		'about_our_beginnings' => array( 'group' => 'about', 'default' => '#our-beginnings', 'label' => 'Our Beginnings' ),
		'podcast_conversations' => array( 'group' => 'podcast', 'default' => '#conversations', 'label' => 'Explore the Conversations' ),
		'articles_rf_article_title' => array( 'group' => 'articles', 'default' => '#rf-article-title', 'label' => 'Back to Top' ),
		'not_found_404_test' => array( 'group' => 'not_found', 'default' => '#test', 'label' => 'Entrepreneur test' ),
		'home_hero_programs' => array( 'group' => 'home', 'default' => '#programs', 'label' => 'Hero — Check Our Programs' ),
		'home_hero_https_vimeo_com_1223972706' => array( 'group' => 'home', 'default' => 'https://vimeo.com/1223972706', 'label' => 'Hero — Watch on Vimeo' ),
		'home_hero_test' => array( 'group' => 'home', 'default' => '#test', 'label' => 'Hero — Entrepreneur test' ),
		'home_programs_test' => array( 'group' => 'home', 'default' => '#test', 'label' => 'Programs — Entrepreneur test' ),
		'home_cta_programs' => array( 'group' => 'home', 'default' => '#programs', 'label' => 'Closing section — Check Our Programs' ),
		'home_cta_test' => array( 'group' => 'home', 'default' => '#test', 'label' => 'Closing section — Entrepreneur test' ),
		'home_test_test' => array( 'group' => 'home', 'default' => '#test', 'label' => 'Test — Entrepreneur test' ),
		'header_site_header_test' => array( 'group' => 'header', 'default' => '#test', 'label' => 'Entrepreneur test' ),
		'os_step_1' => array( 'group' => 'momentum_os', 'default' => '#os-step-1', 'label' => 'Step navigation — step 1' ),
		'os_step_2' => array( 'group' => 'momentum_os', 'default' => '#os-step-2', 'label' => 'Step navigation — step 2' ),
		'os_step_3' => array( 'group' => 'momentum_os', 'default' => '#os-step-3', 'label' => 'Step navigation — step 3' ),
		'os_step_4' => array( 'group' => 'momentum_os', 'default' => '#os-step-4', 'label' => 'Step navigation — step 4' ),
		'os_step_5' => array( 'group' => 'momentum_os', 'default' => '#os-step-5', 'label' => 'Step navigation — step 5' ),
		'os_step_6' => array( 'group' => 'momentum_os', 'default' => '#os-step-6', 'label' => 'Step navigation — step 6' ),
		'not_found_home' => array( 'group' => 'not_found', 'default' => '/', 'label' => 'Back to homepage' ),
		'articles_podcast' => array( 'group' => 'articles', 'default' => '/rules-for-success/', 'label' => 'Back to podcast / explore more conversations' ),
		'shared_logo' => array( 'group' => 'header', 'default' => '/', 'label' => 'Logo destination — header and footer' ),
);
